# Generated by Django 5.2 on 2025-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_alter_register_email_alter_register_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
