# Generated by Django 5.2 on 2025-05-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('delivery_boy', models.CharField(max_length=30, null=True)),
                ('product_status', models.CharField(default='order placed', max_length=30)),
                ('order_date', models.DateTimeField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.register')),
            ],
        ),
    ]
