# Generated by Django 5.2 on 2025-07-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0007_delivery_boy_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.register')),
            ],
        ),
    ]
